// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: testdata/v1/input.proto

package testdatav1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TestValidateError with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TestValidateError) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestValidateError with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestValidateErrorMultiError, or nil if none found.
func (m *TestValidateError) ValidateAll() error {
	return m.validate(true)
}

func (m *TestValidateError) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetMetadataPublic()))
		i := 0
		for key := range m.GetMetadataPublic() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetMetadataPublic()[key]
			_ = val

			// no validation rules for MetadataPublic[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, TestValidateErrorValidationError{
							field:  fmt.Sprintf("MetadataPublic[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, TestValidateErrorValidationError{
							field:  fmt.Sprintf("MetadataPublic[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return TestValidateErrorValidationError{
						field:  fmt.Sprintf("MetadataPublic[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if m.GivenName != nil {

		if l := utf8.RuneCountInString(m.GetGivenName()); l < 2 || l > 5 {
			err := TestValidateErrorValidationError{
				field:  "GivenName",
				reason: "value length must be between 2 and 5 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.FamilyName != nil {

		if l := utf8.RuneCountInString(m.GetFamilyName()); l < 2 || l > 5 {
			err := TestValidateErrorValidationError{
				field:  "FamilyName",
				reason: "value length must be between 2 and 5 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return TestValidateErrorMultiError(errors)
	}

	return nil
}

// TestValidateErrorMultiError is an error wrapping multiple validation errors
// returned by TestValidateError.ValidateAll() if the designated constraints
// aren't met.
type TestValidateErrorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestValidateErrorMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestValidateErrorMultiError) AllErrors() []error { return m }

// TestValidateErrorValidationError is the validation error returned by
// TestValidateError.Validate if the designated constraints aren't met.
type TestValidateErrorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestValidateErrorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestValidateErrorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestValidateErrorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestValidateErrorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestValidateErrorValidationError) ErrorName() string {
	return "TestValidateErrorValidationError"
}

// Error satisfies the builtin error interface
func (e TestValidateErrorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestValidateError.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestValidateErrorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestValidateErrorValidationError{}
